### ISSUE TITLE
About missing implementation detail in eq. 10.

### ISSUE THREAD

**Issue by a18700** [ahmetius/LP-DeepSSL#6]
Hello, first thanks for the great paper, and i have a question on the point that has not described in the paper.

according to `line 309 of lp/db_semisuper.py', the one-hot label vector is normalized by the class population, and it's very new implementation detail to me which is not described in the paper.

Please can you give me any evidence for this?

Thank you.
Sincerely.

**Comment by ahmetius** [comment]
Hello,

This simply normalizes the y vector by the class frequency, so that the sum of its elements will be 1. Since the y vector is constructed from originally labeled images, and that it is balanced across classes (the number of labeled images is the same for all classes), and that Z is further normalized on Line 317, this normalization should not have any impact.
